### ISSUE TITLE
Annoying flash

### ISSUE THREAD

**Issue by trinajstica** [toolbar-dial/toolbar-dial#35]
Hello,
in dark mode of the toolbar dial, if I press home button there is white flash and it's annoying. You can see it better if you set some backgorund picture... is this possible to fix?

Thanks!

**Comment by lucaseverett** [comment]
Hi @trinajstica,

I don't think there is anything I can do to improve that, but I'm going to look into it to see what can be done to improve it.

**Comment by lucaseverett** [comment]
@trinajstica This should be fixed in release 2.5. Please let me know if it looks better to you.

**Comment by trinajstica** [comment]
Thank you, it is working as expected. No white flickering! Great work. Thanks. :)

**Comment by lucaseverett** [comment]
Fixed by e5a39151b15f970e1fb4b7cc863c4d8a3d4d66a7.
